name: prepare

on:
  workflow_dispatch:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run clang-format style check for C/C++ code
        uses: jidicula/clang-format-action@v4.11.0
        with:
          clang-format-version: 14
          check-path: '.'
          fallback-style: Chromium

      - name: Install dependencies
        run: ./install_sfml

      - name: Run build
        run: make
